# Linear Regression

In [ ]:
# Implement Linear Regression using scikit-learn

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# Generate synthetic data
np.random.seed(0)
X = 2 * np.random.rand(200, 1)
y = 4 + 3 * X + np.random.randn(200, 1)

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

In [ ]:
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
r2_score = model.score(X_test, y_test)
print(f"R^2 Score: {r2_score}")
mae = np.mean(np.abs(y_test - y_pred))
print(f"Mean Absolute Error: {mae}")

# What is MSE, R^2 Score, and MAE
# MSE (Mean Squared Error) measures the average of the squares of the errors—that is, the average squared difference between the estimated values and the actual value.
# R^2 Score (Coefficient of Determination) indicates the proportion of the variance in the dependent variable that is predictable from the independent variable(s). An R^2 of 1 indicates that the regression predictions perfectly fit the data.
# MAE (Mean Absolute Error) measures the average magnitude of the errors in a set of predictions, without considering their direction. It’s the average over the test sample of the absolute differences between predicted values and actual values.

In [ ]:
# Plot the results

plt.scatter(X, y, color='blue', label='Data points')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Regression line')
plt.xlabel('X')
plt.ylabel('y')
plt.title('Linear Regression using scikit-learn')
plt.legend()
plt.show()

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
print(iris.DESCR)

# Logistic Regression

In [ ]:
# Logistic Regression using Scikit-learn

from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [ ]:
# Load and show the iris dataset
iris = load_iris()
X = iris.data
y = iris.target
print(iris.DESCR)

In [ ]:
# Perform logistic regression on the iris dataset

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [ ]:
# Evaluate the model

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

In [ ]:
# Create a dataset for logistic regression with two classes and plot as well

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# Generate a synthetic dataset
X, y = make_classification(n_samples=200, n_features=2, n_informative=2, n_redundant=0, n_clusters_per_class=1,
                            random_state=42)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Create and train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
# Plot the decision boundary
x_min, x_max = X_test[:, 0].min() - 1, X_test[:, 0].max() + 1
y_min, y_max = X_test[:, 1].min() - 1, X_test[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.01),
                     np.arange(y_min, y_max, 0.01))
Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)
plt.contourf(xx, yy, Z, alpha=0.8)
plt.scatter(X_test[:, 0], X_test[:, 1], c=y_test, edgecolors='k', marker='o')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.title('Logistic Regression Decision Boundary (Test Set)')
plt.show()

# Fetch values for precision, recall, f1-score, and support from classification report
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print(report)


# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)



In [ ]:
# Explain the accuracy, classification report, and confusion matrix
# Accuracy is the ratio of correctly predicted observations to the total observations. It gives a quick overview of how well the model is performing.
# The Classification Report provides a detailed breakdown of precision, recall, F1-score, and support for each class. Precision is the ratio of correctly predicted positive observations to the total predicted positives. Recall (sensitivity) is the ratio of correctly predicted positive observations to all actual positives. F1-score is the weighted average of Precision and Recall.
# The Confusion Matrix is a table that is often used to describe the performance of a classification model. It shows the true positives, true negatives, false positives, and false negatives, allowing for a more detailed analysis of the model's performance across different classes.

# What is precision, recall, F1-score, and support
# Precision is the ratio of correctly predicted positive observations to the total predicted positives. It indicates how many of the predicted positive cases were actually positive.
# Recall (sensitivity) is the ratio of correctly predicted positive observations to all actual positives. It indicates how many of the actual positive cases were captured by the model.
# F1-score is the weighted average of Precision and Recall. It is a useful metric when you need to balance both precision and recall, especially in cases of imbalanced datasets.
# Support is the number of actual occurrences of each class in the dataset. It indicates how many samples belong to each class.

# Precision vs Recall
# Precision and Recall are two important metrics used to evaluate the performance of classification models, especially in scenarios where the classes are imbalanced.
# Precision focuses on the accuracy of the positive predictions made by the model. High precision means that when the model predicts a positive class, it is usually correct.
# Recall, on the other hand, focuses on the model's ability to capture all actual positive instances. High recall means that the model is able to identify most of the positive cases in the dataset.

# Example
# Consider a medical test for a disease. If the test has high precision, it means that when it indicates a person has the disease, it is very likely to be correct (few false positives). If the test has high recall, it means that it successfully identifies most of the people who actually have the disease (few false negatives). Depending on the context, one may prioritize precision over recall or vice versa.

# Decoding the confusion matrix
# In a confusion matrix, each row represents the instances in a predicted class while each column represents the instances in an actual class (or vice versa). The diagonal elements represent the number of correct predictions for each class, while the off-diagonal elements represent misclassifications. By analyzing the confusion matrix, one can identify which classes are being confused with each other and assess the model's performance in more detail.

# Example
# Confusion Matrix:
# [[10  0  0]
#  [ 0  9  1]
#  [ 0  2  8]]
# In this example, for class 0, there were 10 correct predictions and no misclassifications. For class 1, there were 9 correct predictions and 1 misclassification as class 2. For class 2, there were 8 correct predictions and 2 misclassifications as class 1.

In [ ]:
# Understanding Entropy and Information Gain in Decision Trees

# Entropy is a measure of uncertainty or impurity in a dataset. In the context of decision trees, it quantifies the disorder or randomness in the class labels of the data points. A dataset with high entropy has a mix of different classes, while a dataset with low entropy has mostly one class.
# Information Gain is a metric used to measure the effectiveness of a feature in classifying the training data. It quantifies the reduction in entropy achieved by splitting the dataset based on a particular feature. The feature that provides the highest information gain is chosen for the split at each node in the decision tree.


# Create a more comprehensive dataset for demonstration
ex_dataset = [
    ("Adult-Y", "Rich", "Yes"),
    ("Adult-Y", "Low", "No"), 
    ("Adult-Y", "Medium", "No"),
    ("Adult-Y", "Rich", "Yes"),
    ("Middle-aged", "Rich", "Yes"),
    ("Middle-aged", "Low", "No"),
    ("Middle-aged", "Medium", "Yes"),
    ("Middle-aged", "Medium", "No"),
    ("Middle-aged", "Low", "No"),
    ("Senior", "Rich", "Yes"),
    ("Senior", "Low", "No"),
    ("Senior", "Medium", "Yes"),
    ("Senior", "Rich", "Yes")
]

# ex_dataset = [i for i in ex_dataset if i[1] == 'Medium']
ex_dataset.sort(key=lambda x: x[0])
# Print as table
print(f"{'AgeGroup':<12} {'IncomeLevel':<12} {'OwnsCar':<8}")
print("-" * 32)
for row in ex_dataset[1:]:
    print(f"{row[0]:<12} {row[1]:<12} {row[2]:<8}")

In [ ]:
# Decision Trees

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the Decision Tree model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

In [ ]:
# Plot the decision tree
from sklearn.tree import plot_tree
plt.figure(figsize=(12,8))
plot_tree(model, filled=True, feature_names=iris.feature_names, class_names=iris.target
                     .astype(str))

plt.show()


In [ ]:
# Random forest and ensemble learning

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Create and train the Random Forest model
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)
# Predict on the test set
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

In [ ]:
# Model evaluation and comparison on ROC, AUC, cross-validation

# Since we already have the iris dataset loaded and split, we can proceed directly
# Create and train the Logistic Regression model
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.model_selection import cross_val_score


model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Predict probabilities on the test set
y_probs = model.predict_proba(X_test)

# For multiclass classification, calculate ROC AUC using 'ovr' (one-vs-rest) strategy
auc = roc_auc_score(y_test, y_probs, multi_class='ovr')
print(f"ROC AUC Score (One-vs-Rest): {auc}")

# Perform cross-validation
cv_scores = cross_val_score(model, X, y, cv=5, scoring='roc_auc_ovr')
print(f"Cross-Validation ROC AUC Scores: {cv_scores}")
print(f"Mean Cross-Validation ROC AUC Score: {np.mean(cv_scores)}")

# Optional: Plot ROC curves for each class
plt.figure(figsize=(10, 8))
for i in range(len(iris.target_names)):
    # Convert to binary classification (one class vs rest)
    y_test_binary = (y_test == i).astype(int)
    y_probs_binary = y_probs[:, i]
    
    fpr, tpr, _ = roc_curve(y_test_binary, y_probs_binary)
    auc_class = roc_auc_score(y_test_binary, y_probs_binary)
    
    plt.plot(fpr, tpr, label=f'{iris.target_names[i]} (AUC = {auc_class:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves for Multiclass Classification')
plt.legend()
plt.show()

In [ ]:
# The ROC (Receiver Operating Characteristic) curves plotted above represent the performance of the Logistic Regression model for each class in a one-vs-rest manner. Each curve shows the trade-off between the True Positive Rate (sensitivity) and the False Positive Rate for different threshold values. The area under each curve (AUC) quantifies the overall ability of the model to discriminate between the positive class and the negative class. An AUC of 1 indicates perfect classification, while an AUC of 0.5 suggests no discriminative power (random guessing). The closer the ROC curve is to the top-left corner, the better the model's performance for that class.

In [ ]:
# Hyperparameter tuning with GridSearchCV

from sklearn.model_selection import GridSearchCV
# Define the parameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs'],
    'max_iter': [100, 200, 300]
}

grid_search = GridSearchCV(model, param_grid, cv=5, scoring='roc_auc_ovr')
grid_search.fit(X_train, y_train)

print("Best Hyperparameters:")
print(grid_search.best_params_)
print(f"Best Cross-Validation ROC AUC Score: {grid_search.best_score_}")